name: Build and publish a Docker image

on: push

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      TAG: python-check
      PAT: ${{ secrets.GITHUB_TOKEN }}
      USER: raviroch
      REGISTRY: ghcr.io
      VERSION: v1

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t ${{ env.TAG }} .

      - name: Login to GHCR
        run: |
          echo ${{ env.PAT }} | docker login ${{ env.REGISTRY }} -u ${{ env.USER }} --password-stdin
          docker tag ${{ env.TAG }} ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.TAG }}:${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.TAG }}:${{ env.VERSION }}
