name: Build and publish a Docker image

on: push

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      TAG: python-check
      PAT: ${{ secrets.GITHUB_TOKEN }}
      USER: raviroch
      REGISTRY: ghcr.io
      VERSION: v1

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.TAG }} .
          docker tag $TAG ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}

      - name: Login and push to GHCR
        run: |
          echo $PAT | docker login ${{ env.REGISTRY }} -u $USER --password-stdin
          docker push ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}

      - name: trivyscan
        uses: bh-ent-tech/bh-shared-workflow/.github/workflows/trivyscan.yaml@main
        with:
          image_name: ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}
          reponame: ${{ github.event.repository.name }}
          version_name: "latest"
          docker_file_path: "."    
          Package_lock: "./shared-workflows"
        secrets: inherit
          
            
          
